#!/usr/bin/env bash
# Script to show information about subdomains

dns_config () {
    script=$(dig "$2"."$1" | grep -Al 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " is a $2 " record and points to " $3}
}

if [ "$#" == 1 ]
then
  dns_config "$1" "www"
  dns_config "$1" "lb-01"
  dns_config "$1" "web-01"
  dns_config "$1" "web-02"
elif [ "$#" == 2 ]
then
  dns_config "$1" "$2"
fi 
