#!/usr/bin/env bash
# Configure Nginx to  contain a custom header for http response on web-01 and web-02
# X-Served-By : hostname
sudo apt-get update
sudo apt-get -y install nginx

# configure firewall 
sudo ufw allow 'Nginx HTTP'

# create directory
sudo mkdir -p /var/www/html

# change file permission
sudo chmod -R 755 /var/www

#  index page
echo 'Hello World!' |sudo tee  /var/www/html/index.html

# error web page
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

# code to configure redirect single page and add header
string_to_replace="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.justicedan.tech permanent;"
sudo sed -i "s/server_name _;/$string_to_replace/" /etc/nginx/sites-enabled/default

# code to configure redirect for 404 error page
string_to_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_to_replacement/" /etc/nginx/sites-enabled/default

# Restart nginx
sudo service nginx restart
