#!/usr/bin/env bash
# Script to configure an Nginx server

sudo apt-get update
sudo apt-get install -y nginx

# Redirect to a named end point such as google.com
echo "Hello World!" | sudo tee /var/ww/html/index.html
replace-string_with="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo -i "s/server_name _;/$replace_string_with/" /etc/ngnx/sites-enabled/default

# Create an error page and add aa redirect for error 404
echo "Ceci n'est pas une page" | sudo /var/www/html/404.html
replace_string_with="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"
sudo -i "s/listen 80 default_server;/$replace_string_with/" /etc/nginx/sites-enabled/default

sudo service nginx restart
