#!/usr/bin/env bash
# script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to my web-01 and web-02 servers
# using round-robin balancer to distribute request 
#  HAProxy should be managed via an init script
# Install and also configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

#editing the config file
server_config=\
"
frontend  justicedan-frontend
        bind *:80
        mode http
        default_backend justicedan-backend
backend justicedan-backend
        balance roundrobin
        server  171998-web-01 34.239.248.111:80 check
        server 171998-web-02 54.175.89.17:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
