#!/usr/bin/env bash
# Alternative anwer to 0 but fix is short and sweet.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
