#!/usr/bin/env bash
#This script dispays numbers from 1 to 20
#displays 4 and the bad luck from chinz for the 4th iteration
#displays and then bad luck from japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17 loop iteration
i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from China"
			;;

		17)
			echo "bad luck from Italy"
			;;
		esac
	((i++))
done
