#!/usr/bin/env bash
# A bash script that configure Nginx to run as nginx user

# replace '#user' and its value in the config file
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replace port 80 with 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# change owner permission to allow read and write
chmod 664 /etc/nginx/nginx.conf
# kill apache process if running
pkill apache2
# start nginx with new user
sudo -u nginx service nginx start 
