#!/usr/bin/env bash
# A bash script that fixes buggy web server to run nginx as nginx on port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed "s/80/8080/g" /etc/nginx/sites-available/default
chmod 664 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
